sudo: false
language: python
jobs:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      sudo: required
      dist: xenial
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=readme
    - python: 3.6
      env: TOXENV=linters
  fast_finish: true
  allow_failures:
    - python: 3.6
      env: TOXENV=linters

# install: pip install tox codecov
install: pip install tox
script: tox
after_success:
  - coverage report -m

